-- Create tables
CREATE TYPE user_role AS ENUM ('admin', 'staff');
CREATE TYPE car_status AS ENUM ('available', 'reserved', 'sold');
CREATE TYPE inquiry_status AS ENUM ('new', 'contacted', 'closed');

-- Profiles table
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL,
  role user_role NOT NULL DEFAULT 'staff',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Companies table
CREATE TABLE companies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Models table
CREATE TABLE models (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT REFERENCES companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Cars table
CREATE TABLE cars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id BIGINT REFERENCES models(id) ON DELETE CASCADE,
  year INTEGER NOT NULL,
  price DECIMAL NOT NULL,
  mileage INTEGER NOT NULL,
  fuel_type TEXT NOT NULL,
  transmission TEXT NOT NULL,
  color TEXT NOT NULL,
  status car_status NOT NULL DEFAULT 'available',
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Car images
CREATE TABLE car_images (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT REFERENCES cars(id) ON DELETE CASCADE,
  image_url TEXT NOT NULL,
  is_cover BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Customers table
CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  email TEXT UNIQUE,
  city TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Inquiries table
CREATE TABLE inquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT REFERENCES cars(id) ON DELETE SET NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE,
  message TEXT,
  status inquiry_status NOT NULL DEFAULT 'new',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Sales table
CREATE TABLE sales (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  car_id BIGINT REFERENCES cars(id) ON DELETE SET NULL,
  customer_id BIGINT REFERENCES customers(id) ON DELETE SET NULL,
  sale_price DECIMAL NOT NULL,
  sale_date DATE DEFAULT CURRENT_DATE,
  payment_method TEXT,
  handled_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE models ENABLE ROW LEVEL SECURITY;
ALTER TABLE cars ENABLE ROW LEVEL SECURITY;
ALTER TABLE car_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE sales ENABLE ROW LEVEL SECURITY;

-- Helper function to check if user is admin/staff without recursion
CREATE OR REPLACE FUNCTION public.check_user_role(target_role user_role)
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND role = target_role
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_admin_or_staff()
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM profiles
    WHERE id = auth.uid() AND (role = 'admin' OR role = 'staff')
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Profiles: Users can read their own profile, admins can read all
CREATE POLICY "Users can read own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Admins can read all profiles" ON profiles FOR ALL USING (
  (SELECT role FROM profiles WHERE id = auth.uid()) = 'admin' -- Basic check
);
-- Note: If the above still fails in your specific Supabase version, use:
-- CREATE POLICY "Admins can read all profiles" ON profiles FOR ALL USING (check_user_role('admin'));


-- Public read access for cars, companies, models, images
CREATE POLICY "Public read cars" ON cars FOR SELECT USING (TRUE);
CREATE POLICY "Public read companies" ON companies FOR SELECT USING (TRUE);
CREATE POLICY "Public read models" ON models FOR SELECT USING (TRUE);
CREATE POLICY "Public read car images" ON car_images FOR SELECT USING (TRUE);

-- Admin/Staff write access
CREATE POLICY "Staff/Admin manage companies" ON companies FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'admin' OR role = 'staff'))
);
CREATE POLICY "Staff/Admin manage models" ON models FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'admin' OR role = 'staff'))
);
CREATE POLICY "Admin manage cars" ON cars FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);
CREATE POLICY "Staff read cars" ON cars FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'admin' OR role = 'staff'))
);
CREATE POLICY "Admin manage car images" ON car_images FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Inquiries
CREATE POLICY "Public insert inquiries" ON inquiries FOR INSERT WITH CHECK (TRUE);
CREATE POLICY "Staff/Admin manage inquiries" ON inquiries FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'admin' OR role = 'staff'))
);

-- Customers
CREATE POLICY "Public insert customers" ON customers FOR INSERT WITH CHECK (TRUE);
CREATE POLICY "Staff/Admin manage customers" ON customers FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'admin' OR role = 'staff'))
);

-- Sales
CREATE POLICY "Staff/Admin manage sales" ON sales FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'admin' OR role = 'staff'))
);

-- Handle profile creation on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, name, role)
  VALUES (new.id, new.raw_user_meta_data->>'name', 'staff');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
